{% set name = "zfel" %}
{% set version = "0.99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6dc73b189aac2802ea5da041a6402f28bd032e04212e5182969d6f3eeea374df

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy

test:
  imports:
    - zfel
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/slaclab/zfel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 1D FEL code in Python
  description: |
    1D FEL code in Python  

extra:
  recipe-maintainers:
    - ChristopherMayes
